### ISSUE TITLE
Upgrade to 1.1.0 with existing data not possible

### ISSUE THREAD

**Issue by doits** [westonganger/paper_trail-association_tracking#11]
With the latest 1.1.0 update, the ` :foreign_type` column is introduced. It has `null: false`, which means it cannot be added to existing data (since there will be `null` values unless they are explicitly computed). I tried a manual migration to add the column:

```
-- add_column(:version_associations, :foreign_type, :string, {:null=>false})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "foreign_type" contains null values
```

Is it possible to update to the latest version with existing data?

**Comment by benhutton** [comment]
We're running into this too!

**Comment by netcitylife** [comment]
Same problem

**Comment by westonganger** [comment]
Sorry guys. I've just fixed this on master. This update ensures compatibility with existing data containing existing null values. Can you test it out for me and see if its all working well. 

Also this latest commit includes a generator for the migration for the new column using `rails g paper_trail_association_tracking:add_foreign_type_to_version_associations`. These upgrade steps are now documented in the changelog too.

**Comment by westonganger** [comment]
v1.1.1 is now released which fixes this.
