### ISSUE TITLE
Change version association database and table name.

### ISSUE THREAD

**Issue by phrsouza** [westonganger/paper_trail-association_tracking#16]
I'm trying to use papetrail and papetrail association track storing its data into a different database.

I achieved that for the `PaperTrail::Version` model by [following the papetrail doc](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes)

I saw the following comment on the `PaperTrail::VersionAssociation` class:

```ruby
  # This is the default ActiveRecord model provided by PaperTrail. Most simple
  # applications will only use this and its partner, `Version`, but it is
  # possible to sub-class, extend, or even do without this model entirely.
  # See the readme for details.
```
But I'm not quite sure how to change the behavior of the `PaperTrail::VersionAssociation` as I did in the  `PaperTrail::Version`.

I also [posted this question on stackoverflow](https://stackoverflow.com/questions/61372070/modify-papertrail-version-associations-class)

**Comment by westonganger** [comment]
I appreciate that you asked this question in the issues section and want to encourage that.

It is likely this functionality has not been implemented and will likely require a PR to achieve the functionality you desire. If you would like to take a stab at this it let me know, otherwise I will try to take a look into this when I have time and see what I can come up with.

**Comment by phrsouza** [comment]
@westonganger I believe that this is not a priority since we have a workaround that is patching the `Papertrail::VersionAssociation` in a initializer:

```ruby
#config/initializers/paper_trail.rb

PaperTrail.config.track_associations = true

PaperTrail::VersionAssociation.class_eval do
  self.table_name = 'version_associations'
  connects_to database: { writing: :versions_db, reading: :versions_db }
end
```

**Comment by westonganger** [comment]
Yes I understand, however someone may want to use different databases per model. We should be able to support this case.

**Comment by tomgilligan** [comment]
Love [this](https://github.com/westonganger/paper_trail-association_tracking/issues/16#issuecomment-621166459) solution.  Unfortunately it is broken in Rails [6.1](https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/connection_handling.rb#L82):

```
"`connects_to` can only be called on ActiveRecord::Base or abstract classes" 
```

I think per model configuration would be ideal but as far as I can tell there is no other per model configuration yet (so a bit trickier to get going with a PR).  The main point of integration as far as app models are concerned is the `has_paper_trail` method defined in the base paper trail gem and not this extension gem, so not sure how to add to it here.

I'm thinking of adding an abstract class that is parent of `VersionAssociation` and child of `ActiveRecord::Base` to resolve this.  I'm guessing that when client applications extend `VersionAssociation` it is mostly for reasons other than selecting a different database (don't want to break things for the majority).

**Comment by westonganger** [comment]
This functionality is now implemented on master, thanks to @sobrinho . https://github.com/westonganger/paper_trail-association_tracking/commit/d5e15f61f3887ae45d0f9fb4acf7de478f175df5
