### ISSUE TITLE
Mistake in README ?

### ISSUE THREAD

**Issue by bjacquet** [westonganger/paper_trail-association_tracking#20]
Hello! I'm going through README — to install this gem on my project — and there's a mismatch between the documentation and what actually happened.

On section **Install** it says:
> Then run `rails generate paper_trail_association_tracking:install` which will do the following two things for you:
>
>   1. Create a `version_associations` table
>   2. Set `PaperTrail.config.track_associations = true` in an initializer

But what actually happened was that it set `PaperTrail.config.track_associations = false`!
Either the documentation is wrong or the task is wrong. 🤷 

Cheers!

**Comment by westonganger** [comment]
Thanks for pointing this out. v2.1.1 is now released which fixes this.
