### ISSUE TITLE
Problem loading after upgrading to paper_trail 12.0

### ISSUE THREAD

**Issue by smeeks** [westonganger/paper_trail-association_tracking#27]
Just upgraded to paper_trail 12.0 today. Now when I try:

require "paper_trail"
require "paper_trail-association_tracking"

I get an error:

/ruby-2.5.3/gems/paper_trail-association_tracking-2.1.1/lib/paper_trail_association_tracking/version_concern.rb:19:in `block in <module:VersionConcern>': undefined method `scope' for PaperTrail::VersionConcern:Module (NoMethodError)

**Comment by westonganger** [comment]
Its appears this is related to https://github.com/paper-trail-gem/paper_trail/pull/1281 where they switched to a different loading/initialization methodology. We will need to lazy load our files in a similar manner.

PR wanted if anyone wants to take a stab at it, otherwise I will try to look into this soon.

**Comment by jaredbeck** [comment]
Dang. I didn't realize this would impact PT-AT. For the short-term, PT-AT users can constrain PT to < 12 without missing much.

I learned a bunch about Railties in the process of working on https://github.com/paper-trail-gem/paper_trail/pull/1281, let me know if I can help answer any questions about load order. I also documented some of what I learned in comments in `paper_trail-12.0.0/lib/paper_trail/frameworks/rails/railtie.rb`, if that helps.

**Comment by westonganger** [comment]
@jaredbeck I have attempted to make the appropriate changes on the branch [`change_load_order`](https://github.com/westonganger/paper_trail-association_tracking/tree/change_load_order) I am having trouble figuring out why its not loading correctly still. Think you could take a look at it and help sort this out?

**Comment by CoryFoy** [comment]
I know it's obvious, but wanted to put out there a simple repro is to create a new Rails project, add `paper_trail` and it's setup, then add `paper_trail-association_tracking` and attempt to run the set up script. 

```/Dev/.rvm/gems/ruby-2.6.3/gems/paper_trail-association_tracking-2.1.1/lib/paper_trail_association_tracking/version_concern.rb:19:in `block in <module:VersionConcern>': undefined method `scope' for PaperTrail::VersionConcern:Module (NoMethodError)```

**Comment by CoryFoy** [comment]
@westonganger It looks like your `lib/paper_trail_association_tracking/frameworks/rails.rb` is including the `paper_trail` railtie instead of the one you wrote. Adding in `require "paper_trail_association_tracking/frameworks/rails/railtie"` at least causes the Railtie to be loaded, but the initializer is still not running. (I tested by putting a `raise` before the `initializer` and noting that it didn't do anything without that additional line). Looking into it all now.

**Comment by CoryFoy** [comment]
@westonganger So making that change above and commenting out the "scope" line it looks like Association Tracking works with your branch. I don't know why Scope isn't being found yet, though.

**Comment by CoryFoy** [comment]
@westonganger Ok, after playing around with a bunch of stuff, I was able to get everything running on your branch by adding the line `require "paper_trail/frameworks/active_record"` in https://github.com/westonganger/paper_trail-association_tracking/compare/change_load_order#diff-b8156b0f39674521ca93eb580acad301d601a66373eb2e8ced8f9f095c9f10d9R13. What it looks like is `paper_trail` isn't loaded, so `scope` isn't being found. I don't know if that's the definitive way to do it, but it fixes the immediate issue.

**Comment by hidde-jan** [comment]
Is there any progress? The changes in paper_trails where due to rails 6.1 and 7.0 has dropped in the meantime. Up to date rails apps can only use choose to checkout a branch of this gem currently, which isn't ideal.

**Comment by westonganger** [comment]
@hidde-jan I did merge @CoryFoy changes. After merging I noticed that the loading issues were not actually resolved. So I dont believe the branch of this gem is working correctly.

I dug into it but was personally unable to come up with a working solution here. I would love a PR that properly fixes the loading issues.

**Comment by westonganger** [comment]
Still looking for a PR here if anyone can come up with somthing that works. Would be a big help to the PT community.

**Comment by mgoggin** [comment]
No guarantees but I'll give it a go. I'll look into it first thing in the morning.

**Comment by clinejj** [comment]
I'm not sure if this is helpful, but was looking at the ordering flow changes from the original paper_trail update and came up with a different solution than #28 - ultimately the `scope` problem was because the `VersionConcern` also relies on active record and needs to be loading after (in addition to the `VersionAssociationConcern`).

I made that change and have tests passing for AR 6.0 and 6.1 (5.2 and 7.0 are still failing), but unfortunately using those changes in an actual application don't fix the issue of missing association versions:
https://github.com/westonganger/paper_trail-association_tracking/compare/master...clinejj:load-order-updates

**Comment by westonganger** [comment]
@clinejj I believe I had already tried adding the require active_record and that was not the real solution to the issue. There is more to it than that. I think that @jaredbeck should be helping us with this.

**Comment by jaredbeck** [comment]
> I think that @jaredbeck should be helping us with this, seems like no one else understands what happened here.

I can't take the lead on this, but my offer to help still stands:

> I learned a bunch about Railties in the process of working on https://github.com/paper-trail-gem/paper_trail/pull/1281, let me know if I can help answer any questions about load order. 

Please let me know what specific questions you have about load order and I'll do my best to answer them.

> I also documented some of what I learned in comments in paper_trail-12.0.0/lib/paper_trail/frameworks/rails/railtie.rb, if that helps.

If there's any documentation I can improve in PT itself, I'll do my best to help there too.

**Comment by chubchenko** [comment]
Regarding "missing <version_associations> association" I have found the [solution](https://github.com/chubchenko/paper_trail-association_tracking/pull/2)

```ruby
# lib/paper_trail_association_tracking/frameworks/rails/railtie.rb

config.to_prepare do
  ::PaperTrail::Version.include(::PaperTrailAssociationTracking::VersionConcern)
end
```

But I still have doubts that this is a good decision.

**Comment by westonganger** [comment]
@chubchenko if you make this change and run the tests does it help our situation?

**Comment by westonganger** [comment]
I would like to point out the changes I made that did not resolve our issues. So that others can learn from my experiences.

Commit: https://github.com/westonganger/paper_trail-association_tracking/commit/a84cd2e5798328a9ae0eddb6e130f750a614fc2f

**Comment by chubchenko** [comment]
@westonganger here are the [results](https://github.com/chubchenko/paper_trail-association_tracking/runs/4907713546?check_suite_focus=true) of my build. As you can see, I still have failed builds, but they are all related to Rails 7.

**Comment by westonganger** [comment]
Looking real good. Send out that PR and I can work on Rails 7 if no one else wants to.

**Comment by westonganger** [comment]
All issues with PT v12+ have now been resolved in master

**Comment by westonganger** [comment]
v2.2.0 is now released which contains the necessary changes for PT 12+ to function correctly.
