### ISSUE TITLE
Thoughts on repo and gem ownership

### ISSUE THREAD

**Issue by jaredbeck** [westonganger/paper_trail-association_tracking#3]
Weston, 

Here are some options for repo ownership:

1. You own the repo, and don't have any other committers. I'm totally happy with this.
2. You own the repo, and invite the PT team (Andy, Ben, and myself) as committers
3. The repo moves to the [paper-trail-gem organization](https://github.com/paper-trail-gem) and we'd give you the highest permissions we could in that scenario.

Similarly, with gem ownership:

1. You are the only owner of the gem. I am fine with this.
2. You grant gem-pushing permission to the PT team

I'm fine with any mix of the above. I can imagine a situation where PT needs to change the interface we share (eg. changing how something like `RecordTrail#record_create` works, and it would be convenient to push corresponding changes to this repo and/or push a new gem.

Let me know what you're thinking, and I'll be happy with whatever you choose.

**Comment by westonganger** [comment]
I will own the repo. For now I'll add you as a contributor and others can be added later if they want to. I will handle most of the maintaining since you've already shown express disinterest however am happy to have your updates when needed.

**Comment by jaredbeck** [comment]
Sounds good, thanks. Yeah, the main reason I'd want to work on PT-AT would be if PT needed to change something that PT-AT was patching.
