### ISSUE TITLE
Support for rails 7.0

### ISSUE THREAD

**Issue by estebanz01** [westonganger/paper_trail-association_tracking#31]
Hello! 👋 

It would be interesting to see some support on rails 7.0. The parent gem already has an issue logged and they seems to be working actively on it: https://github.com/paper-trail-gem/paper_trail/issues/1358

**Comment by westonganger** [comment]
I have now added Rails 7 to the CI suite. For now there is nothing more to do in that regard. 

Right now we have a pressing need to resolve #27 first

**Comment by westonganger** [comment]
All issues with Rails 7+ and PT v12+ have now been resolved in master

**Comment by westonganger** [comment]
v2.2.0 is now released which contains support for Rails 7.
