### ISSUE TITLE
"assoc.klass" does not work for a relation 'belongs_to_active_hash'

### ISSUE THREAD

**Issue by smptmhr** [westonganger/paper_trail-association_tracking#43]
Hello, @westonganger .

I faced the problem below when I use PT-AT gem with paper_trail.

# version info
```
Rails 7.0.4
db: mysql:8.0.26

paper_trail (12.3.0)
  activerecord (>= 5.2)
  request_store (~> 1.1)
paper_trail-association_tracking (2.2.1)
  paper_trail (>= 12.0)
```
 
# problem

My code has `Product` and `ProductMaster` classes.
```ruby
def Product < ApplicationRecord
  has_paper_trail
  belongs_to_active_hash :product_master, class_name: ProductMaster
end
active_hash (3.1.1)
  activesupport (>= 5.0.0)

```

```ruby
class ProductMaster < ActiveHash::Base
  include ActiveHash::Associations

  self.data = [
    {
      id: 1,
      name: 'product_a',
      rank: 1000,
    },
    {
      id: 2,
      name: 'product_b',
      rank: 2000,
    },
    {
      id: 3,
      name: 'product_c',
      rank: 3000,
    },   
  ]

  has_many :products
end
```

When updating a `Product` instance, updating failed with following error messages.
```
Rails couldn't find a valid model for ProductMaster association.
Please provide the :class_name option on the association declaration.
If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.
```

I saw `record_update` method in `lib/paper_trail_association_tracking/record_trail.rb` and debug the method.
Finally,I found the error is occurring here.

https://github.com/westonganger/paper_trail-association_tracking/blob/c8e8b2cc06f25d8563338ee08a95e6d9e2e335bf/lib/paper_trail_association_tracking/record_trail.rb#L177

`assoc` cannot return class name because `klass` is not defined in ActiveHash, I guess.

# solution suggesting
In my local environment, using `constantize` works for updating a model which have associations defined by both `belongs_to_active_hash` and `belongs_to(active_record)`.
```ruby
elsif ::PaperTrail.request.enabled_for_model?(assocclass.name.constantize)
```

I created PR but it failed(I don't know why ...)
- https://github.com/westonganger/paper_trail-association_tracking/pull/44

**Comment by westonganger** [comment]
Closing as this seems out of scope.
