### ISSUE TITLE
Planning to change PT-AT from runtime dependency to dev. dependency

### ISSUE THREAD

**Issue by jaredbeck** [westonganger/paper_trail-association_tracking#7]
Getting ready for the release of PT 10, seemed like a good time for this planned change.

https://github.com/paper-trail-gem/paper_trail/pull/1133/commits/db9c392d2f685e0dde970bf2e8b15b7eb3178f0e

PT will keep PT-AT as a dev. dependency and continue to run all existing association-tracking related tests for as long as is practical. The only change here is that PT-AT users will have to add it to their own Gemfile.

Any concerns? Any further instructions we should include in the PT 10.0.0 changelog entry?

**Comment by westonganger** [comment]
Well dropping the runtime dependency happened quicker then expected... However my only concern is that this change does not happen silently. Should there be any pre-removal notice during the 10.x series, kind of like a deprecation? This could look like the following on your end.

```ruby
module PaperTrailAssociationTracking
  module Config
    PT_AT_ERROR = 'Please add PT-AT gem to your Gemfile'

    def track_associations=(val)
      raise PT_AT_ERROR
    end

    def track_associations?
      raise PT_AT_ERROR
    end
  end
end
```

**Comment by jaredbeck** [comment]
> .. dropping the runtime dependency happened quicker then expected...

Yeah, it's only been three months, but we're doing a major version release so it's a good opportunity to make breaking changes.

> However my only concern is that this change does not happen silently. 

It's in the changelog, but yeah people often don't read changelogs.

> Should there be any pre-removal notice during the 10.x series, kind of like a deprecation? This could look like the following on your end.

Sounds good. Want to make a PR?

So, PT-AT has to be `require`d after PT, right? So, will the order in the Gemfile matter? Should we tell people to put PT-AT *after* PT in their Gemfile?

**Comment by jaredbeck** [comment]
Closing via https://github.com/paper-trail-gem/paper_trail/pull/1141. Thanks!
